#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get install -y haproxy

sudo chown -R "$USER" /etc/default/haproxy
sudo chown -R "$USER" /etc/haproxy/
sudo chmod 666 /etc/haproxy/haproxy.cfg

sudo echo "ENABLED=1" >> /etc/default/haproxy

sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 54.166.164.192:80 check\n\tserver server2 54.90.7.176:80 check\n" >> /etc/haproxy/haproxy.cfg'

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
